image: registry.nic.cz/turris/reforis/reforis/reforis-image

stages:
    - test
    - build
    - publish

before_script:
    - apt-get update && apt-get install -y make
    - npm install

test:
    stage: test
    script:
        - make test

lint:
    stage: test
    script:
        - make lint

build:
    stage: build
    script:
        - make pack
    artifacts:
        paths:
            - dist/foris-*.tgz

publish_beta:
    stage: publish
    only:
        refs:
            - dev
    script:
        - make publish-beta

publish_latest:
    stage: publish
    only:
        refs:
            - master
    script:
        - make publish-latest
